### ISSUE TITLE
server could not process packet because no encryption mapping exists

### ISSUE THREAD

**Issue by ChristianHohlfeld** [networkprotocol/yojimbo#101]
How can I resolve this issue? I'm trying to send a message and the server logs this message. Thanks!

**Comment by gafferongames** [comment]
I need more information to diagnose what is going on. Is this packet being sent between the client and server after a session has been established?

**Comment by ChristianHohlfeld** [comment]
I will create a standalone project for issue 99, it happens only sporadically after the connection has been established.

**Comment by gafferongames** [comment]
Is there anything else happening, aside from this print? It's common that if a UDP packet arrives on your server, from some other application on your LAN, that it will print this ut.

**Comment by gafferongames** [comment]
Also, what port # are you listening on? Try changing it, and this may go away. I've seen this happen sporadically when another application sends data to your port, and yojimbo correctly ignores it (since it does not belong to your protocol).

Let me know. Unless you are seeing anything else happening, other than these printfs, this is benign.

**Comment by gafferongames** [comment]
OK reopening. If there is a side-effect then that makes sense this is unlikely just random packets on the LAN. Looking forward to the repro!

**Comment by ChristianHohlfeld** [comment]
I couldn't reproduce the encryption issue, so I guess you can close this one.
I set up a repo and a small tutorial. You can find all sources on www.ragdoll-tv.de. I'm writing the next article explaining the code and maybe some basics of cocos2d-x soon.
