### ISSUE TITLE
Issue with mobile networks and ipv6

### ISSUE THREAD

**Issue by mpope9** [networkprotocol/yojimbo#75]
Due to apparent issues with mobile networks and ipv4, I am attempting to get a client to connected to a server using ipv6.  Using my local ipv6 address I can't seem to get the insecure server to see any traffic from the insecure client.  I can, however, get the server to detect garbage UDP packets while running from the ipv6 address.  I pass the same address to both the client and the server and the client times out while attempting to connect.  The same results occur while trying to connect to a remote server.

I can connect successfully using the while running using ipv4, both locally and remotely.

Can you see any obvious flaws that I'm missing?

**Comment by mpope9** [comment]
And, also when I attempt to generate an ipv6 address using the matcher it comes out with every other byte reversed.

**Comment by mpope9** [comment]
Ahh, I see why the address is 'scrambled', the `htons` takes care of network byte order?  

Well I've whittled it down to the `netcode_socket_send_packet()` function.  It seems that `sendto` fails with the errno: `invalid argument`.  

Alittle more info, I'm running OSX.

**Comment by mpope9** [comment]
Well, it looks like I was not setting the client to have an ipv6 address.  Which makes sense that it has to have that, if connecting to an ipv6 server.

Follow up question 1: Are connect tokens able to have one ipv4 and one ipv6 address in them?

Follow up question 2: I haven't seen any mechanism to switch a client from ipv4 to ipv6.  Would you suggest just destroying the client and creating a new one with ipv6?

**Comment by gafferongames** [comment]
Yes, tokens can have an IPv4 address and IPv6 address in them. They support multiple addresses. You can see the spec for connect tokens on the netcode.io project.

It has been a while since I've worked with this library, so I don't remember. But the point at which you pass the client an address, eg. "0.0.0.0" or "::0" to bind to, is where it picks IPv4 vs. IPv6.

I don't remember if this is start/stop, but if it is, then that's all you need to do.

If it's in the CTOR, then yes, you need to destroy the client and recreate it to switch addresses.

As a feature request in the future, it seems reasonable to support a dual-stack server, such that it has a socket for IPv6, and a socket for IPv4 connections simultaneously.

**Comment by mpope9** [comment]
I see.  Thank you for the reply.
