### ISSUE TITLE
Documentation on how to use the library

### ISSUE THREAD

**Issue by ChristianHohlfeld** [networkprotocol/yojimbo#97]
Is there any documentation on how to integrate yojimbo into cocos2d-x or any other c++ game engine? I'm talking about a basic scenario including send/receive/serialize. Thanks!

**Comment by FredGithub** [comment]
I'm not sure if you're waiting for an official answer from the project owner, but I can give you some help based on how I implemented Yojimbo in my project. I will keep this answer brief, and simplify all code snippets, since a full explanation could easily be several pages long and I'm not really sure what you need. But feel free to ask about specific parts and I will try to answer as best as I can. Note that I'm not familiar with Cocos2d-x but this should be the same for any C++ engine.

The first thing you will need is a way to run your game "headless" (with no window / rendering context, only a console) for the server. Game servers usually run in VPS machines where there is no real use for a window or rendering stuff to the screen. My server's main class is called `GameServer`, and it handles everything the server needs to do. The different parts of Yojimbo you need on the server are `Server`, `ClientServerConfig` and `Adapter`. 

The `Server` is the main part, used to receive and send messages. The `ClientServerConfig` allows you to configure the server: connection timeout, memory used, but most importantly, the different channels (reliable, unreliable). The `Adapter` allows you to get callbacks when a client connects or disconnects, and is also responsible for providing Yojimbo with the `MessageFactory`. Both the `ClientServerConfig` and the `Adapter` are shared between client and server. Here is what it could look like:

```
// only a test message for now
enum class GameMessageType {
    TEST,
    COUNT
};

// two channels, one for each type that Yojimbo supports
enum class GameChannel {
    RELIABLE,
    UNRELIABLE,
    COUNT
};

// the client and server config
struct GameConnectionConfig : public yojimbo::ClientServerConfig {
    GameConnectionConfig()  {
        numChannels = 2;
        channel[(int)GameChannel::RELIABLE].type = yojimbo::CHANNEL_TYPE_RELIABLE_ORDERED;
        channel[(int)GameChannel::UNRELIABLE].type = yojimbo::CHANNEL_TYPE_UNRELIABLE_UNORDERED;
    }
};

// the adapter
class GameAdapter : public yojimbo::Adapter {
public:
    explicit GameAdapter(GameServer* server = NULL) :
        m_server(server) {}

    yojimbo::MessageFactory* CreateMessageFactory(yojimbo::Allocator& allocator) override {
        return YOJIMBO_NEW(allocator, GameMessageFactory, allocator);
    }

    void OnServerClientConnected(int clientIndex) override {
        if (m_server != NULL) {
            m_server->ClientConnected(clientIndex);
        }
    }

    void OnServerClientDisconnected(int clientIndex) override {
        if (m_server != NULL) {
            m_server->ClientDisconnected(clientIndex);
        }
    }

private:
    GameServer* m_server;
};

// the message factory
YOJIMBO_MESSAGE_FACTORY_START(GameMessageFactory, (int)GameMessageType::COUNT);
YOJIMBO_DECLARE_MESSAGE_TYPE((int)GameMessageType::TEST, TestMessage);
YOJIMBO_MESSAGE_FACTORY_FINISH();
```

Note that the adapter will have a null `GameServer` pointer when used on the client. If you prefer, you can also create a different adapter for the client, but it needs to provide Yojimbo with the same `MessageFactory` as the server.

Let's take a look at the `TestMessage` class and briefly cover basic serialization:

```
class TestMessage : public yojimbo::Message {
public:
    int m_data;

    TestMessage() :
        m_data(0) {}

    template <typename Stream>
    bool Serialize(Stream& stream) {
        serialize_int(stream, m_data, 0, 512);
        return true;
    }

    YOJIMBO_VIRTUAL_SERIALIZE_FUNCTIONS();
};
```

Yojimbo uses a unified serialization system for both reading from and writing to a `Stream`. It takes a bit of getting used to, and for more complex messages, you will sometimes have to split the code path, but I won't get into details. Here we just want to read/write a simple int, so we use the `serialize_int` helper. There are several serialization helpers provided by Yojimbo, and you will probably need to define several more to cover the needs of your game.

The `GameServer` will then have a `GameConnectionConfig`, a `GameAdapter` and a `Server`, and initialize everything like so:

```
static const uint8_t DEFAULT_PRIVATE_KEY[yojimbo::KeyBytes] = { 0 };
static const int MAX_PLAYERS = 64;

GameServer::GameServer(const yojimbo::Address& address) :
    m_adapter(this),
    m_server(yojimbo::GetDefaultAllocator(), DEFAULT_PRIVATE_KEY, address, m_connectionConfig, m_adapter, 0.0)
{
    // start the server
    m_server.Start(MAX_PLAYERS);
    if (!m_server.IsRunning()) {
        throw std::runtime_error("Could not start server at port " + std::to_string(address.GetPort()));
    }

    // print the port we got in case we used port 0
    char buffer[256];
    m_server.GetAddress().ToString(buffer, sizeof(buffer));
    std::cout << "Server address is " << buffer << std::endl;

    // ... load game ...
}

void GameServer::ClientConnected(int clientIndex) {
    std::cout << "client " << clientIndex << " connected" << std::endl;
}

void GameServer::ClientDisconnected(int clientIndex) {
    std::cout << "client " << clientIndex << " disconnected" << std::endl;
}
```

Note the use of a null private key. How to make secure connections to the server is a topic on its own, so I won't talk about it now. But for development, you will be running both the server and the client on your own machine so you're fine with insecure connections.

Also note that the `GameServer` takes an `Address`. The IP part of the address must be set to the external IP address of the machine. You are free to chose the port. For development, just use "127.0.0.1" and a port of your liking.

The server will need a custom game loop, running at a fixed timestep. Game loops and whether to use fixed timestep or not is also a topic on its own, but for netcode I feel fixed timestep, for both server and client, is unevitable. I chose to run my server at 60fps. Here is what it looks like:

```
void GameServer::Run() {
    float fixedDt = 1.0f / 60.0f;
    while (m_running) {
        double currentTime = SystemUtils::Time();
        if (m_time <= currentTime) {
            Update(fixedDt);
            m_time += fixedDt;
        } else {
            SystemUtils::Sleep(m_time - currentTime);
        }
    }
}
```

In the Update method, there are 3 methods of the `Server` class that you need to call: `AdvanceTime`, `ReceivePackets` and `SendPackets`. Note that the order is very important. Using another order might add a couple frames of delay to your server's latency. Here is what it looks like:

```
void GameServer::Update(float dt) {
    // stop if server is not running
    if (!m_server.IsRunning()) {
        m_running = false;
        return;
    }

    // update server and process messages
    m_server.AdvanceTime(m_time);
    m_server.ReceivePackets();
    ProcessMessages();

    // ... update game ...
    // ... send game state to clients ...

    m_server.SendPackets();
}
```

The `ProcessMessage` function consists in looping over all the connected clients and read the messages received from each of them:

```
void GameServer::ProcessMessages() {
    for (int i = 0; i < MAX_PLAYERS; i++) {
        if (m_server.IsClientConnected(i)) {
            for (int j = 0; j < m_connectionConfig.numChannels; j++) {
                yojimbo::Message* message = m_server.ReceiveMessage(i, j);
                while (message != NULL) {
                    ProcessMessage(i, message);
                    m_server.ReleaseMessage(i, message);
                    message = m_server.ReceiveMessage(i, j);
                }
            }
        }
    }
}

void GameServer::ProcessMessage(int clientIndex, yojimbo::Message* message) {
    switch (message->GetType()) {
    case (int)GameMessageType::TEST:
        ProcessTestMessage(clientIndex, (TestMessage*)message);
        break;
    default:
        break;
    }
}

void GameServer::ProcessTestMessage(int clientIndex, TestMessage* message) {
    // ... process test message ...
}
```

Let's take a look at the client. You need a `Client`, and the same `ClientServerConfig` and `Adapter` as the server. My game is divided in screens, and the screen handling the online game is called `OnlineGameScreen`. It looks like this:

```
OnlineGameScreen::OnlineGameScreen(const yojimbo::Address& serverAddress) :
    m_client(yojimbo::GetDefaultAllocator(), yojimbo::Address("0.0.0.0"), m_connectionConfig, m_adapter, 0.0)
{
    uint64_t clientId;
    yojimbo::random_bytes((uint8_t*)&clientId, 8);
    m_client.InsecureConnect(DEFAULT_PRIVATE_KEY, clientId, m_serverAddress);
}
```

Yojimbo requires each client to have a `clientId`. In a game with user accounts, this would typically be the user id. While in development, or if you don't have accounts in your game, you can just pass a random `uint64_t` number. Note that with a secure connection, the `clientId` wouldn't be set by the client, but would come inside a connection token received from the web backend, so clients cannot spoof their identity. But I won't talk about this for now.

The client is now connecting, you can check the state of the connection in your game loop to know when the connection is established. Note that later on, you will also want to detect disconnection, and try to reconnect the client. Just like on the server, you also need to update the `Client` by calling the `AdvanceTime`, `ReceivePackets` and `SendPackets` methods.

For testing purposes, let's also send a `TestMessage` when the player presses a key:

```
void OnlineGameScreen::Update(float dt) {
    // update client
    m_client.AdvanceTime(m_client.GetTime() + dt);
    m_client.ReceivePackets();

    if (m_client.IsConnected()) {
        ProcessMessages();

        // ... do connected stuff ...

        // send a message when space is pressed
        if (KeyIsDown(KEY_SPACE)) {
            TestMessage* message = (TestMessage*)m_client.CreateMessage((int)GameMessageType::TEST);
            message->m_data = 42;
            m_client.SendMessage((int)GameChannel::RELIABLE, message);
        }
    }

    m_client.SendPackets();
}

void OnlineGameScreen::ProcessMessages() {
    for (int i = 0; i < m_connectionConfig.numChannels; i++) {
        yojimbo::Message* message = m_client.ReceiveMessage(i);
        while (message != NULL) {
            ProcessMessage(message);
            m_client.ReleaseMessage(message);
            message = m_client.ReceiveMessage(i);
        }
    }
}

void OnlineGameScreen::ProcessMessage(yojimbo::Message* message) {
    switch (message->GetType()) {
    case (int)GameMessageType::TEST:
        ProcessTestMessage((TestMessage*)message);
        break;
    default:
        break;
    }
}

void OnlineGameScreen::ProcessTestMessage(TestMessage* message) {
    std::cout << "Test message received from server with data " << message->m_data << std::endl;
}
```

The client now sends a `TestMessage` when a key is pressed, and will also log to the console when receiving one. Let's change the server so that when it receives a `TestMessage` it will log to the console, and answer the same message back to the client:

```
void GameServer::ProcessTestMessage(int clientIndex, TestMessage* message) {
    std::cout << "Test message received from client " << clientIndex << " with data " << message->m_data << std::endl;
    TestMessage* testMessage = (TestMessage*)m_server.CreateMessage(clientIndex, (int)GameMessageType::TEST);
    testMessage->m_data = message->m_data;
    m_server.SendMessage(clientIndex, (int)GameChannel::RELIABLE, testMessage);
}
```

Note that we used the `RELIABLE` channel here. I won't get into details but you will want to use the reliable channel for important and unfrequent messages such as initialization or chat messages, and the unreliable channel for messages sent every frame like the game state.

You should now be able to run the server, run the client, have it connect to the server, and send and receive test messages. I'm gonna stop here since this already got a lot longer than I planned, but I hope this was helpful and don't hesitate to ask!

I'm actually in the process of making a game networking demo using Yojimbo, to showcase common netcode techniques (client side prediction, interpolation, "lag compensation" of hitscan weapons, etc). I mostly do it for myself but I might share it or maybe write an article, if I feel it's good enough for that!

**Comment by gafferongames** [comment]
Wow. This is great!

**Comment by ChristianHohlfeld** [comment]
Hey that's great, thanks for your time and effort. I really didn't expect such a great answer. Thank you very very much!

**Comment by ChristianHohlfeld** [comment]
Hey @FredGithub, I implemented your code and I managed to compile yojimbo and cocos2d-x for win32. I got a strange issue thoug... When I try to create a GameServer object, I got an Exception: Exception thrown: write access violation.
control was nullptr.

The constrol_construct method 'static void control_construct(control_t* control)' gets a NULL reference for control_t*. 

Here are my the Classes:
https://gist.github.com/ChristianHohlfeld/5fac4b7362054d94257896bea6fad9ce

My basic usage is like that:
```
	InitializeYojimbo();
	yojimbo_log_level(YOJIMBO_LOG_LEVEL_DEBUG);
	int serverPort = 4000;
	Address gameServerAddress("127.0.0.1", serverPort);

```

**Comment by gafferongames** [comment]
static void control_construct(control_t* control)' gets a NULL reference
for control_t*

^--- This function is not part of yojimbo, so it must be something about
your environment!

**Comment by ChristianHohlfeld** [comment]
@gafferongames I tried the exact same code on my macbook (Desktop App). Same thing. The function can be found here: https://github.com/networkprotocol/yojimbo/blob/master/tlsf/tlsf.c  (line 782).

**Comment by gafferongames** [comment]
Ah. TLSF is the allocator we use...

**Comment by gafferongames** [comment]
Did you remember to initialize the yojimbo library? I'll bet that's it... :)

**Comment by ChristianHohlfeld** [comment]
Thats's my call:
```
	InitializeYojimbo();
	yojimbo_log_level(YOJIMBO_LOG_LEVEL_DEBUG);
	int serverPort = 4000;
	Address gameServerAddress("127.0.0.1", serverPort);
```
So I guess I initialized it, correct me if I forgot something.

**Comment by ChristianHohlfeld** [comment]
And when I run
`GameServer gameServer(gameServerAddress);`
the game crashes.

**Comment by gafferongames** [comment]
You'll have to debug this. This isn't caused by the library, but most
likely the interaction of the library with something unique to the
environment you are running it in.

cheers

- Glenn

**Comment by ChristianHohlfeld** [comment]
Yea, I clearly hooked up something wrong here. But thanks for your time!

**Comment by FredGithub** [comment]
I felt like giving a try running your project, and it actually asserts trying to allocate the server memory because `config.serverGlobalMemory` is 0. That is because you pass an uninitialized config to the `Server`. C++ initializes class variables in the order they are written. In your example, you have:

```
GameAdapter m_adapter;
yojimbo::Server m_server;
GameConnectionConfig m_connectionConfig;
```

Change it to:

```
GameConnectionConfig m_connectionConfig;
GameAdapter m_adapter;
yojimbo::Server m_server;
```

And it should work!

**Comment by ChristianHohlfeld** [comment]
@FredGithub awesome, got it working. Thanks!

**Comment by gafferongames** [comment]
Hey, somebody create a pull request for a USAGE.md with the content in this issue? I think it would be great to put in front of folks on the front page.

**Comment by FredGithub** [comment]
Will do
